# Generated by Django 4.1.1 on 2022-09-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_hours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houravailable',
            options={'verbose_name': 'Hour Available', 'verbose_name_plural': 'Hour Availables'},
        ),
    ]
